amgut/db/populate_test.sql
amgut/lib/data_access/test_ag_data_access.py

There were some functions that are not being called in any of the handlers.  I deleted the tests for those functions.

changes needed for tests to pass

---

amgut/lib/data_access/sql_connection.py

This change to the code the executes stored procedures should abort the transaction if execution of a stored procedure fails.  I need to figure out how to test this, since it will affect all of AG and *not* just the labadmin site...

Roll back transaction if execution of proc fails

---

scripts/ag

@squirrelo, can you review please?

BUG: fixes #362

---

amgut/handlers/auth_handlers.py
amgut/handlers/human_survey.py
amgut/handlers/participant_overview.py

@adamrp @ElDeveloper, possible to review? Should resolve alot of the 405s

BUG: redirect to portal if not going via nav

---

amgut/db/patches/0004.sql
amgut/lib/data_access/ag_data_access.py
scripts/ag

@beaugunderson, can you review please? Should be quick

Migrate handout kits

---

amgut/handlers/auth_handlers.py
amgut/lib/data_access/ag_data_access.py
amgut/templates/no_auth_help_request.html

Add bcrypt check and fix to kit registration

---

amgut/handlers/base_handlers.py

BUG: head method incorrectly specified

---

amgut/handlers/sample_overview.py

ENH: short circuit if no barcode, fixes #383

---

amgut/templates/portal.html

DCT: ducttape on what likely is a null participant name

---

ag_config.txt.example
amgut/lib/config_manager.py
amgut/webserver.py

Fixes biocore/american-gut-web#391

Move COOKIE_SECRET to the config_manager

---

amgut/lib/data_access/ag_data_access.py

This was causing the webserver to crash when fetching elevation data failed.

Need to use None instead of '' for stored proc

---

amgut/handlers/portal.py
amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py
amgut/templates/portal.html

This allows the user to request their verification code be resent if something goes wrong, rather than having to contact us directly to get it.

Add resend verification code to portal

---

amgut/handlers/taxa_summary.py

@squirrelo @adamrp @ElDeveloper, possible for quick review please? This is a bug that impacts production

BUG: added sitebase to taxa summary link

---

amgut/lib/data_access/ag_data_access.py

BUG:Clear promoted survey ID on participant delete

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0006.sql

This will address parts of #410

Use zipcodes table instead of info in ag_login

---

README.md
scripts/ag

That was embarrassing - had some git problems that needed to be addressed
So this PR is only added a couple of minor changes
* Updating README
* Adding in dbname parameter. This will also users with a specified username to create test databases through the ag script

DOC: Updating the README

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0008.sql
amgut/db/populate_test.sql

Discussed in calls and emails with @wasade and @squirrelo. These tables should have constraints. I also reorganized the layout in the DBS file so that the relationships between these tables is easier to see visually.
The test code had to be modified to comply with the new constraints.

Add constraints to barcode-related tables

---

amgut/lib/data_access/procedures/ag_authenticate_user.sql

Quick doc change, no need for review

Updated comment

---

amgut/lib/data_access/ag_data_access.py

@squirrelo @adamrp, possible for quick review please?

BUG: date_signed needs to be cast to be serialized

---

amgut/lib/data_access/ag_data_access.py

Changes SQL in a small way to check by ag_login_id, not supplied_kit_id

Check barcode access by login, not kit

---

amgut/handlers/new_participant.py
amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py
amgut/templates/new_participant.html

Somehow 5 people made it through the survey giving a blank name and email. Not sure how, but htis catches it and has them consent with a proper name and email.

Blank participant fix

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0010.sql
amgut/db/populate_test.sql

~~Depends on #428~~
This adds two tables to the database, one for storing the external surveys available, and one to store the answers to said surveys in JSON format, on a per survey basis.

Third party survey tables

---

amgut/handlers/download.py
amgut/handlers/sample_overview.py
amgut/handlers/taxa_summary.py
amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py
amgut/templates/403.html
amgut/templates/no_auth_403.html
amgut/templates/sample_overview.html
amgut/webserver.py

Knocking out a few of the open issues, and tightening up access

Issues cleanup

---

amgut/lib/data_access/env_management.py

Error from moving the function over.

Fix path to procedures

---

amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py

Easy access to link on how to interpret the handout.

Add link to addendum

---

amgut/lib/data_access/ag_data_access.py

Removing the first set of functions that their count was 0.
I can't test this locally, so test this before merging (although if the count is 0 it shouldn't change anything).
I highly recommend to set up travis. Is there any limitation to not have travis set up?

Removing the count 0 functions from ag-data-access

---

amgut/lib/startup_tests.py
amgut/webserver.py

This tests patch number and barcode number. Also adds framework for making sure environment and runtime assumptions are true before starting server.

Add startup testing

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0013.sql
amgut/lib/data_access/env_management.py
scripts/ag

Adds patch to delete the large test barcodes from the system. Also allows verbose patching.

Delete test barcodes

---

amgut/db/patches/0017.sql

This attaches barcodes to the proper projects.

Move around a bunch of barcodes

---

amgut/db/patches/0018.sql

@squirrelo, can you review quickly please?

BUG: update mm associations

---

amgut/templates/register_user.html

Fixes check to validate country chosen in chosen dropdown.

Update validator for chosen

---

amgut/handlers/add_sample.py
amgut/templates/add_sample.html

Every sample was being submitted using the participant_human handler, regardless of what it actually was.

Log sample using proper handler

---

amgut/db/patches/0024.sql

Remove the promoted survey question from pet surveys.

Add pet survey patch

---

amgut/lib/data_access/test/test_ag_data_access.py

Covers:
- `get_user_for_kit`.
- `get_menu_items`.
- `check_if_consent_exists`.
- `get_user_info`.
:us:-gut

TST: Add more tests

---

amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/test/test_ag_data_access.py
amgut/lib/util.py

This adds tests for ag_set_pass_change_code, update_kit_password, ag_verify_kit_password_change_code, and authenticateWebAppUser

Change password tests

---

amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/test/test_ag_data_access.py

This should add the last tests needed. Should be green now!

Finish db conn tests

---

.travis.yml
amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/env_management.py
amgut/lib/data_access/sql_connection.py
amgut/lib/data_access/test/test_ag_data_access.py
amgut/lib/data_access/test/test_sql_connection.py
amgut/lib/startup_tests.py

This transitions away from the hodge-podge of SQL handling and standardizes on the transaction object from qiita.

Add transaction object

---

amgut/handlers/add_sample.py
amgut/templates/add_sample.html
amgut/templates/add_sample_overview.html
amgut/templates/participant_overview.html
amgut/test/__init__.py
amgut/test/test_add_sample.py
amgut/test/tornado_test_base.py
amgut/webserver.py
licences/qiita.txt
setup.py

This adds the first tests for tornado to american gut, in the form of the add_sample pages. This also found a lot of bugs, so the ones that were caught were fixed as well.

Test add_sample.py

---

amgut/handlers/portal.py
amgut/lib/util.py

Remove asd

---

amgut/handlers/human_survey.py
amgut/lib/data_access/sql_connection.py

Commit was removed from get_postgres_cursor() when transitioning to qiita version. put that back. Also fix string issue so we can serialize date object.

Fix commit issues

---

amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py
amgut/templates/sample_overview.html

Changed text when data aren't available

---

amgut/lib/data_access/survey.py
amgut/lib/data_access/test/test_survey.py

This adds all tests to the survey object.

Test survey

---

amgut/lib/data_access/ag_data_access.py

This fixes a bug where some valid UUIDs were being flagged as invalid.

Fix how UUID checked

---

.gitignore
amgut/handlers/open_humans.py
amgut/lib/util.py
amgut/static/js/open_humans.js
amgut/static/vendor/js/js.cookie.js
amgut/templates/open-humans.html
setup.py
tox.ini

This pull request contains updates for the Open Humans connections process, mostly aimed at providing a better user experience for that process.
It's nearly ready to merge (I'd like to do a bit more local testing) but it's ready for feedback. :sparkles:

Open Humans connection process update

---

amgut/handlers/open_humans.py

Fixes an issue currently occurring in production.

Handle ValueError in Open Humans handler

---

amgut/handlers/open_humans.py
amgut/static/js/open_humans.js

...to workaround [this bug in Python pre-2.7.10](https://bugs.python.org/issue22931).

fix Open Humans issue by base64 encoding cookie

---

amgut/db/patches/0031.sql

This adds 2015 as the first birth year in the dropdown.

Add 2015 as a birth year

---

amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py

Tiny PR to change the wording of age range.

Change 6 weeks -> 3 months

---

amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py

Small PR to change the wording

Associate/Log sample -> Assign sample

---

amgut/webserver.py

Log to /var/log/
Log using project locale and port only, so the filename doesn't change every restart.

Change logging for ease of use

---

amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py

Tiny PR for changing contact on consent docs.

Update contact for consent docs

---

amgut/db/patches/0036.sql
amgut/lib/data_access/test/test_survey.py

This adds the two new questions from the IRB amendment to the main AG survey.

Add new questions to survey

---

amgut/handlers/open_humans.py
amgut/handlers/participant_overview.py
amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/test/test_ag_data_access.py

Requires #603 
Updates the open humans interface code to send information on the main human survey to open humans.
@beaugunderson please review if you can, since this is open humans.

Update open humans survey for get_survey_id changes

---

README.rst

DOC: Add missing -n

---

amgut/handlers/personal_microbiome_overview.py
amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py
amgut/templates/personal_microbiome_overview.html
amgut/webserver.py

@EmbrietteH, for the personal microbiome survey. Note, I did not add any tests as the handler is minimal, please let me know if you'd like something in though.

ENH: consent page for persaonl microbiome survey

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0040.sql

Dear all,
I edited the plate mapper database structure. First I changed the data type of col and row into smallint. Then, given that I started editing, I changed a few other things too (see below). Please let me know if you think something isn't right.
Four tables had column "email", two were NOT NULL and the other two were nullable. I made them all nullable.
Two primary keys were assigned in "run_protocol_plate". I guess that they are not supposed to. I removed them.
Renamed "protocol_plate" as "library_plate". I think [**library**](http://www.illumina.com/techniques/sequencing/ngs-library-prep.html) is the right term here. (Protocol is to prep(are) library, library is to be sequenced).
Renamed "target_gene" as "[**targetted**](http://www.pacb.com/applications/targeted-sequencing/)", …

Plate mapper db update

---

amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/test/test_ag_data_access.py
amgut/lib/util.py

Delete sample bug

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0040.sql

@sjanssen2 found that table "protocol_targeted" lacks "name" and "notes". So I added them.

Plate mapper protocol_target name and notes

---

amgut/handlers/participant_overview.py
amgut/lib/config_manager.py
amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/sql_connection.py
amgut/lib/data_access/test/test_sql_connection.py
amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py
amgut/lib/util.py
amgut/templates/participant_overview.html
amgut/test/test_add_sample.py
amgut/webserver.py

Fix for:
An error message is popping up when participants try to access the participant profile for their animal samples. We have tried on the test account as well and find the same error when hovering over Animal Samples --> clicking animal participant profile. Just wanted to give you a heads up!

Bugfix surveyoverview

---

amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py

Rob's wrong number: 858-246-1194 now 858-246-1184
HRPP's wrong number: 858-657-5100 now 858-246-7444
addresses issue #633

corrected phone number of Rob and HRPP

---

amgut/db/patches/0040.sql

Add missing birth years

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/scrub.sql

I've updated the DB schema and HTML files to match the contents of the live database. The only tables missing where the labadmin user tables.
I'm also adding to the repository a script to scrub the database for identifiable information. Please, review that file carefully and raise any concern and/or missing columns/tables that I've missed.
I'm currently running the script in a screen in the test system with a copy of last night's database. It is taking quite a while to run, which I think it is normal due to the nature of the operations and the size of the DB.

Adding scrub script

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0041.sql

Merge #651 first to see my changes.
Some of the assumptions about the data changed from the original DB design. In this PR I'm adding a link between the study and the plate so we know which studies are going to be plated.

Link plate study

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0041.sql

A couple of changes in the patch.

Sample plate fixes

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0041.sql

I need to do this small change in the DB to support one of the comments from @wasade - should be fast

Separating target gene and subfragment

---

amgut/db/ag.dbs
amgut/db/ag.html
amgut/db/patches/0041.sql

Forgot to add a couple of columns

Adding qPCR values

---

amgut/handlers/auth_handlers.py
amgut/handlers/change_pass_verify.py
amgut/handlers/change_password.py
amgut/handlers/forgot_password.py
amgut/handlers/help_request.py
amgut/handlers/human_survey.py
amgut/handlers/portal.py
amgut/handlers/retrieve_kitid.py
amgut/lib/locale_data/american_gut.py
amgut/templates/new_participant.html

This PR updates the consent documentation for the new participant page.

updated consent documentation for new participant page

---

amgut/handlers/human_survey.py
amgut/handlers/participant_overview.py
amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/survey.py
amgut/lib/data_access/test/test_ag_data_access.py
amgut/templates/human_survey_completed.html
amgut/templates/participant_overview.html

Implemented fix to bug involving deleting a survey profile with no samples. Also very slight visual changes for consistency to completed survey and participant overview.

Fix to deleting survey and small visual changes

---

amgut/handlers/participant_overview.py
amgut/lib/data_access/survey.py
amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py

I saw that the thumbnails weren't showing on the real-time site. I changed all vimeo links from http to https. Also there are a few changes to bolding on the consent page for consistency.

Fix to video thumbnails

---

amgut/handlers/animal_survey.py

Adding an animal survey should now say added instead of always saying edited.

Quick change: differentiated adding/editing animal survey

---

amgut/lib/locale_data/american_gut.py
amgut/lib/locale_data/british_gut.py
amgut/templates/help_request.html
amgut/templates/portal.html

Majority of changes from google doc provided by Dom

Participant website

---

amgut/db/patches/0045.sql
scripts/ag

Added patch for 2018 birth year and fixed documentation for script

---

.travis.yml
amgut/handlers/add_sample.py
amgut/lib/data_access/ag_data_access.py
amgut/lib/data_access/test/test_ag_data_access.py

Ping @ElDeveloper, will follow up via email on this

Multivio bug
