biocore/american-gut-web

- amgut/lib/data_access/ag_data_access.py
This adds a more informative error when the survey ID can't be found. Hopefully this will help in tracking down what is going on in #344 and other survey_id related issues.
> Add more informative error for tracing purposes

- amgut/handlers/nojs.py
- amgut/lib/locale_data/american_gut.py
- amgut/lib/locale_data/british_gut.py
- amgut/templates/no_auth_sitebase.html
- amgut/templates/nojs.html
- amgut/webserver.py
Previously, users were hit with repeated 404s at a seizure-inducing rate.
> Adds page that users see when they do not have JS

- amgut/handlers/base_handlers.py
- amgut/handlers/open_humans.py
- amgut/templates/open-humans.html
- amgut/webserver.py
In addition to this code the setting `BASE_URL` also needs to be set to:
```
https://microbio.me/AmericanGut/
```
if it's not already. :)
I've tested this locally by proxying HTTP requests to `http://localhost/AmericanGut/*` to a running instance of `american-gut-web` with its `SITEBASE` set to `/AmericanGut`.
> Fixes for authentication redirects and Open Humans integration

- amgut/lib/locale_data/american_gut.py
Reflects UCSD. British Gut does not need to be updated. Example of render is below.
@elainewolfe, does this look correct? 
@ElDeveloper @adamrp, can you merge please assuming @elainewolfe gives the okay?
> Updated shipping address

- amgut/lib/data_access/ag_data_access.py
The errors were previously left unlogged and as such undetectable. This makes them logged as part of the tornado log file.
> Add logging for try/excepts in ag_data_access

- amgut/templates/add_sample_overview.html
The images used for showing human vs pet vs environmental were broken. This fixes the URL used so they show again.
> Fix sample logging image links

- amgut/handlers/human_survey_completed.py
- amgut/handlers/new_participant.py
- amgut/lib/data_access/ag_data_access.py
- amgut/lib/locale_data/american_gut.py
- amgut/lib/locale_data/british_gut.py
- amgut/lib/mail.py
- amgut/templates/new_participant.html
This is needed before final deploy. Sends the consent form as an email to the person after the survey is completed and consent is entered on the database.
> Email consent

- amgut/templates/sitebase.html
Quick fix to make it less confusing for users. If no barcodes are available for logging, the option is no longer shown.
> Hide "log sample" if no barcodes remaining

- amgut/handlers/human_survey.py
- amgut/handlers/human_survey_completed.py
This makes it so you only get a consent form email on first pass at the survey when creating a new participant. It will no longer try and email you after editing a survey.
> Fix multi-email issue

- amgut/lib/data_access/ag_data_access.py
Previously the database column was lowercased, but not the search term itself. This fixes that.
> Lowercase search term to be in line with database search

- amgut/lib/locale_data/american_gut.py
- amgut/lib/locale_data/british_gut.py
- amgut/templates/add_sample_overview.html
This adds a "[NAME] - Human Source" and "[NAME] - Animal Source" to the logging to stop people being confused and not realizing their name corresponds to a human sample.
> Add source info to logging

- amgut/lib/data_access/ag_data_access.py
@squirrelo, this allows access to results from the portal across multiple kits associated with a login ID
> Allow portal to get all results associated with login

- amgut/handlers/auth_handlers.py
- amgut/handlers/base_handlers.py
- amgut/lib/locale_data/american_gut.py
- amgut/lib/locale_data/british_gut.py
- amgut/templates/no_auth_sitebase.html
- amgut/templates/register_user.html
This does some major changes:
* Completely decoupled login and registration. Now, if a user tries to log in with a non-registered kit, they will get a message informing them to register.
* Added `Register Kit` link to no_auth_sitebase.html
* Registration now works in non-authenticated state, then logs the user in once registration has successfully happened.
* Added all appropriate text to locale dicts.
> Fix registration again

- amgut/db/ag.dbs
- amgut/db/ag.html
- amgut/db/patches/0009.sql
- amgut/db/populate_test.sql
- amgut/lib/data_access/ag_data_access.py
This breaks up the handout kits into two tables: one for handout kit info and one for barcodes attached to the handout. This fixes the issue we've seen previously, where each row in the `ag_handout_kits` table for a given kit is exactly the same except for the barcode. this breakout means that each kit now has a single entry in that table, and the deletion of a kit from that table cascades down and deletes the barcodes from the second table. This is a much cleaner representation, as it allows us to properly represent kits with multiple barcodes.
> Fix handouts table - NEEDS REVIEW

- amgut/lib/locale_data/american_gut.py
- amgut/lib/locale_data/british_gut.py
- amgut/templates/human_survey_completed.html
See screenshot. Hopefully more people will take the secondary surveys if the links are more easily picked up on.
> Break out secondary survey links for better readability

- amgut/db/ag.dbs
- amgut/db/ag.html
- amgut/db/initialize.sql
- amgut/db/patches/0011.sql
- amgut/db/populate_test.sql
- amgut/lib/data_access/ag_data_access.py
- amgut/lib/data_access/sql_connection.py
Depends on #429
This moves the barcode table and associated tables to their own schema, keeping the foreign keys from the ag schema.
> Barcodes in own schema

- amgut/db/patches/0015.sql
Since new ag_handout_barcodes table was added to the ag schema, we need to update ag schema permissions as well.
> Update patch for ag and public schemas

- amgut/db/patches/0016.sql
This takes care of the 165 orphan barcodes created somewhere in time without a project.
> Add unknown barcoes to project UNKNOWN

- scripts/ag
just noticed this was broken when I went to apply the new patches to my very old test database.
> fix broken drop_test command

- amgut/db/ag.dbs
- amgut/db/ag.html
- amgut/db/patches/0023.sql
- amgut/lib/data_access/survey.py
This adds an easy way to retire questions. Retired questions will not show in the surveys, but will show in metadata pulldowns. 
This also moves over the old plants question as a retired question, allowing it to be pulled down.
> Migrate old unmappable questions

- setup.py
Tried to run tests but they failed because the requirement 'requests', used from `amgut/handlers/sample_overview.py`, is not specified; I added it to `install_requires` in `setup.py`.
> add missing requirement 'requests'

- amgut/handlers/add_sample.py
- amgut/templates/add_sample.html
This changes the sample logging page to render with a blank form when validation of the form fails.
> Use blank form on logging errors

- amgut/lib/data_access/ag_data_access.py
- amgut/lib/data_access/test/test_ag_data_access.py
This makes logParticipantSample test work. Previously it was using a barcode used in another test, so the interaction between the two was causing stochastic failures depending on the order the tests were run.
> Change barcode for testing

- amgut/handlers/participant_overview.py
- amgut/lib/locale_data/american_gut.py
- amgut/lib/locale_data/british_gut.py
- amgut/templates/participant_overview.html
This adds a simple link to start/continue the vioscreen survey under the survey edit button. It also lets you know if the survey is complete. Example below:
> Add continue/start option for vioscreen to participant overview

- amgut/db/patches/0030.sql
Part of labadmin pulldown fix [#31](https://github.com/biocore/labadmin/issues/31)
> Fix typos for shortnames

- amgut/lib/data_access/ag_data_access.py
Still getting an issue of barcodes not being deleted when registered using the cascade. This makes it explicit.
> Add explicit delete of registered handout barcodes

- amgut/static/js/open_humans.js
- amgut/templates/open-humans.html
Not sure what changed (I looked at recent commits and didn't see anything that would impact this) but @madprime noticed that people linked American Gut to Open Humans were having their participant ID saved and not their survey ID. This did work at one point, though maybe my code relied on something from the database that it shouldn't have. This commit makes it explicit that it's the `survey_id` we're sending.
cc @EmbrietteH
> Small fix for Open Humans

- amgut/db/ag.dbs
- amgut/db/ag.html
- amgut/db/patches/0033.sql
- amgut/lib/data_access/ag_data_access.py
- amgut/lib/data_access/test/test_ag_data_access.py
This ports over the original IBD survey answers as a new question: "what type of IBD?". This will allow pulldown of old survey answers without confusing with the current question of diagnosis by doctor/other. 
This also adds the DB table needed for tracking consent revocation, which is needed by the IRB for yearly reviews.
> Ibd port as retired

- amgut/db/ag.dbs
- amgut/db/ag.html
- amgut/db/patches/0034.sql
- amgut/handlers/participant_overview.py
- amgut/lib/data_access/ag_data_access.py
- amgut/lib/data_access/test/test_ag_data_access.py
- amgut/templates/participant_overview.html
This adds a column to the ag_kit_barcodes table for tracking whether a barcode has been submitted to EBI or not, independent of results being ready. 
Please review this before reviewing [#45](https://github.com/biocore/labadmin/pull/45) in labadmin.
> Track ebi submissions

- amgut/lib/data_access/ag_data_access.py
This fixes an oversight when removing the barcode where the survey ID was left in despite the barcode being un-associated with anything.
> Also null out survey id when removing barcode

- amgut/db/patches/0035.sql
This patches the DB to add access control tables required for labadmin.
The labadmin tables have never been part of the schema shown, hence the lack of html and dbs files.
> Patch for labadmin access controls

- amgut/lib/data_access/ag_data_access.py
- amgut/lib/data_access/sql_connection.py
- amgut/lib/data_access/test/test_ag_data_access.py
- amgut/lib/test/test_util.py
- amgut/lib/util.py
This updates the code for someone revoking consent to have the barcode either returned to be re-associated if the person still has it, or set to withdrawn if the sample has already been sent in. It also adds logic to log when a participant has withdrawn consent.
> Auto-withdraw or release barcodes

- amgut/db/patches/0038.sql
- amgut/lib/data_access/ag_data_access.py
- amgut/lib/data_access/test/test_ag_data_access.py
- amgut/test/test_add_sample.py
This removes the legacy participant_name column in ag_kit_barcodes and fixes all SQL that was using it.
> Centralize participant_name info

- amgut/handlers/participant_overview.py
- amgut/lib/data_access/ag_data_access.py
- amgut/lib/data_access/test/test_ag_data_access.py
This makes the get_survey_id function work with multiple surveys, returning a dict of survey ids keyed to survey taken over the initial return of just a survey_id. It also updates the participant overview page to use this new fix.
> Survey id fix

- amgut/lib/locale_data/british_gut.py
Replacing a strange char in the shipping address of BritishGut, thus Trivis tests should no longer fail.
> bugfix: changed ' char in shipping address

- amgut/handlers/secondary_survey.py
- amgut/templates/participant_overview.html
similar to the primary survey, a participant can now directly navigate to an earlier started secondary survey (surfer, fermented food) and edit his/her answers.
> new feature: edit secondary survey

- amgut/db/scrub.sql
There was an assumption on the labadmin code (and it is being ensured) that the emails are lowercase. However, that was not being enforced on the scrub script, which made fixing the tests quite interesting, since this was a bit hidden.
> Lowering the emails

- amgut/lib/data_access/ag_data_access.py
That is required by the bcrypt library - it does work now
> Encoding passwords

- amgut/db/patches/0043.sql
Question 146, TYPES_OF_PLANTS, was duplicated stemming from what appears to be a copy/paste error between patch [0023](https://github.com/biocore/american-gut-web/blob/master/amgut/db/patches/0023.sql#L10) and [0033](https://github.com/biocore/american-gut-web/blob/master/amgut/db/patches/0033.sql#L19), where the problematic line was not deleted. The entry in patch 0033 does not appear to have relevance to the surrounding code. This patch removes the duplicate entry, and enforces a `UNIQUE` constraint on the table.
> Remove dups

- amgut/db/patches/0044.sql
The labadmin data access method `store_external_survey` stored incorrect results due to an invalid split on `,` without respect to quoted values. All previously stored vioscreen entries are invalid.
> Remove incorrect vioscreen responses

- README.rst
Quick fix as test PR - clone creates the repo directory, the user needs to nav into directory
> nav to project before pip installation

- amgut/handlers/auth_handlers.py
- amgut/lib/locale_data/american_gut.py
- amgut/lib/locale_data/british_gut.py
- amgut/templates/register_user.html
Now should rerender with an error message and previous statements when submitting all entries with an invalid id or pw instead of returning to home page.
> Register kit rerender with previous details on invalid id/pw

- amgut/handlers/human_survey_completed.py
- amgut/lib/util.py
- amgut/test/test_human_survey_completed.py
I failed writing an appropriate unit test for this, because I don't know how to set a secured cookie in the unit test code and would need some help here.
Otherwise, I hope to have fixed the problem by passing the survery_id to the rendering methods, such that existing surveys should be edited to alternatively (if no survey of this type exists) a new survey is created. Please test manually.
> addressing issue #679: Fermentation survey can be created multiple times

- amgut/test/test_auth_handlers.py
My first try to add proper unit tests for a handler class. All comments are appreciated.
> new unit test module for auth_handlers.py

- amgut/templates/sample_overview.html
Temporarily remove the interactive report button as it isn't hooked up to anything yet. This is being commented out as this is a last fix before going live, and the intention is to restore as is.
> MAINT: remove interactive action as it isn't hooked up yet

- amgut/templates/new_participant.html
When the bill of rights PDF opens in the same tab/window, the user has to navigate "back" to return to the new participant page. However, when the user returns to the page, the containers of the consent/assent forms are kept closed and the radio button for age selection is kept selected -- which means the user has to manually select another age and then select the correct age option in order to re-open the correct consent/assent forms.
This is a partial fix for this problem, since it should make the bill of rights PDF open in a new tab or window (preserving the context of the original page). However, I think it'd also be a good idea to fix the problem of the consent/assent containers automatically closing in the future, in case the user ends up navigating back to this page anyway (due to …
> Open bill of rights links in new tab/window
